### ISSUE TITLE
Could not load file or assembly 'Microsoft.Windows.Shell, PublicKeyToken=31bf3856ad364e35' or one of its dependencies

### ISSUE THREAD

**Issue by RobGibbens** [JoergEg/CQRS-Sample#1]
After downloading, compiling, running Raven.Server.exe, and debugging, I get this exception...

Initialization of 'Microsoft.Windows.Controls.Ribbon.RibbonApplicationMenuItem' threw an exception.' Line number '14' and line position '18'.

Could not load file or assembly 'Microsoft.Windows.Shell, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.

I've tried this on two different machines.

**Comment by JoergEg** [comment]
Thank you for pointing this out. It's fixed now.
